### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by alexandrepossebom** [ellisonleao/neovimfiles#1]
Hi, thank you for sharing your dot files.

I did the steps in readme but I got errors in dependencies from your local files:

- gruvbox.vim
- carbon-now.vim

**Comment by ellisonleao** [comment]
hey @alexandrepossebom sorry about that. You can comment those outs or change to the remote address

```lua
use({"ellisonleao/gruvbox.nvim"})
use({"ellisonleao/carbon-now.nvim"})
```

**Comment by alexandrepossebom** [comment]
Thank you for replying.
